services:
  - type: web
    name: seamless-frontend
    env: static
    buildCommand: yarn build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
